name: Publish Packages

on:
    push:
        tags:
            - 'v*.*.*' # Match version tags like v1.0.0
    
    workflow_dispatch: 

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore Unions.sln

            - name: Build
              run: dotnet build Unions.sln --configuration Release --no-restore
            
            # Ensure that the tests must pass 
            # The job will fail automatically if any test fails because `dotnet test` exits with a non-zero code
            - name: Run tests - Tests.AterraEngine.Unions
              run: dotnet run -c Release --no-restore --no-build --framework net9.0
              working-directory: "tests/Tests.AterraEngine.Unions"
            - name: Run tests - Tests.AterraEngine.Unions.Generators
              run: dotnet run -c Release --no-restore --no-build --framework net9.0
              working-directory: "tests/Tests.AterraEngine.Unions.Generators"
                        
            - name: Publish to NuGet
              env:
                  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
              run: |
                  dotnet nuget push src/AterraEngine.Unions/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
                  dotnet nuget push src/AterraEngine.Unions.Generators/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate