name: Publish Packages

on:
  push:
    tags:
      - 'v*.*.*' # Match version tags like v1.0.0

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            framework: [net8.0, net9.0, netstandard2.0]
            project:
                - src/AterraEngine.Unions
                - src/AterraEngine.Unions.Generators

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Unions.sln
        
      - name: Build for framework ${{ matrix.framework }}
        run: dotnet build ${{ matrix.project }} --configuration Release --framework ${{ matrix.framework }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push src/AterraEngine.Unions/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push src/AterraEngine.Unions.Generators/bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate